# Site settings
title: Emily Delbridge
email: ""
description: "Interdisciplinary performance and technology artist, writer, and software engineer"
url: "https://em-twines.github.io"
baseurl: "/arts-website"
facebook_username: ""
twitter_username: ""
instagram_username: ""
github_username:  ""
deviantart_username: ""
flickr_username: ""
discus_shortname: ""
share: true

# Owner/author information
owner:
  name: Emily Delbridge
  avatar: emily-twines-profile.png
  favicon: favicon.ico
  info: An artist's portfolio website

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

# Internal nav
# In development, these will use relative URLs; in production, they use full URLs
nav:
  - INTERACTIVE: "/interactive/"
  - FILM: "/film/"
  - CRITICISM + TALKS: "/criticism/"
  - TECH: "/tech/"
  - ABOUT: "/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
